# Site settings
title: Paul Franz
description: |
  Geospatial. Motion. Web.
  Digital Storyteller.
owner: Paul Franz # or company name
first_published: 2020 # if migrating another site, the year of your first publish
email: paulkfranz@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.paul-franz.com" # the base hostname & protocol for your site
social:
  email: paulkfranz@gmail.com
  vimeo: https://www.vimeo.com/pkfranz
  linkedin-square: https://linkedin.com/in/pkfranz
  twitter: https://twitter.com/pkfranz
  github: https://github.com/pkfranz
  #facebook-official: https://facebook.com/<username>
  #google-plus-square: https://plus.google.com/u/0/+<username>
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
